import Link from "next/link";
import { notFound } from "next/navigation";

import { GameActions } from "@/components/GameActions";
import { LiveGame } from "@/components/LiveGame";
import { Replay } from "@/components/Replay";
import { apiUrl, getGame, listEvents, listTurns, pgnUrl } from "@/lib/api";

export const dynamic = "force-dynamic";

const TERMINAL = new Set(["finished", "aborted"]);

export async function generateMetadata({ params }: PageProps<"/games/[id]">) {
  // `params` is a Promise in Next.js 16.
  const { id } = await params;
  const game = await getGame(id);
  if (!game) return { title: "Game not found · Chessmark" };

  const white = game.players.find((p) => p.colour === "white")?.display_name ?? "White";
  const black = game.players.find((p) => p.colour === "black")?.display_name ?? "Black";
  const finished = TERMINAL.has(game.status);

  const title = `${white} vs ${black} · Chessmark`;
  const description = finished
    ? `${white} vs ${black} — ${game.result} by ${game.termination} in ${game.ply_count} plies.`
    : `${white} vs ${black}, live.`;

  // The card image is generated by `opengraph-image.tsx` next to this file; Next.js wires it up
  // automatically, so only the text needs stating here.
  return {
    title,
    description,
    openGraph: { title, description, type: "article" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function GamePage({ params }: PageProps<"/games/[id]">) {
  const { id } = await params;
  const game = await getGame(id);

  if (!game) notFound();

  const finished = TERMINAL.has(game.status);

  // A finished game needs its turn rows too, to reach the raw payloads behind each ply (LOG-07).
  const [events, turns] = await Promise.all([
    listEvents(id),
    finished ? listTurns(id) : Promise.resolve([]),
  ]);

  return (
    <main className="mx-auto w-full max-w-[1400px] px-5 py-8">
      <div className="mb-5 flex flex-wrap items-center gap-3">
        <Link
          href="/"
          className="font-mono text-[11px] uppercase tracking-[0.16em] text-ink-faint transition-colors hover:text-accent"
        >
          ← Chessmark
        </Link>
        <GameActions pgnHref={pgnUrl(id)} />
      </div>

      {finished ? (
        <Replay game={game} apiUrl={apiUrl} events={events} turns={turns} />
      ) : (
        <LiveGame game={game} apiUrl={apiUrl} initialEvents={events} />
      )}
    </main>
  );
}
