import { notFound } from "next/navigation";

import { GameActions } from "@/components/GameActions";
import { GameView } from "@/components/GameView";
import { Replay } from "@/components/Replay";
import { apiUrl, getGame, getGameTournament, listEvents, listTurns, pgnUrl } from "@/lib/api";

export const dynamic = "force-dynamic";

const TERMINAL = new Set(["finished", "aborted"]);

export async function generateMetadata({ params }: PageProps<"/games/[id]">) {
  // `params` is a Promise in Next.js 16.
  const { id } = await params;
  const game = await getGame(id);
  if (!game) return { title: "Game not found" };

  const white = game.players.find((p) => p.colour === "white")?.display_name ?? "White";
  const black = game.players.find((p) => p.colour === "black")?.display_name ?? "Black";
  const finished = TERMINAL.has(game.status);

  const title = `${white} vs ${black}`;
  const description = finished
    ? `${white} vs ${black} — ${game.result} by ${game.termination} in ${game.ply_count} plies.`
    : `${white} vs ${black}, live.`;

  // The card image is generated by `opengraph-image.tsx` next to this file; Next.js wires it up
  // automatically, so only the text needs stating here.
  return {
    title,
    description,
    alternates: { canonical: `/games/${game.id}` },
    openGraph: { title, description, type: "article" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function GamePage({ params }: PageProps<"/games/[id]">) {
  const { id } = await params;
  const game = await getGame(id);

  if (!game) notFound();

  const finished = TERMINAL.has(game.status);

  // A finished game needs its turn rows too, to reach the raw payloads behind each ply (LOG-07).
  //
  // The event standings are a third request rather than part of the game, because they are six
  // queries against `GET /games/{id}`'s one and the game is what the board waits on. `tournament`
  // on the game is the cheap flag that says whether there is anything to ask for — most games are
  // started by hand, and asking anyway would be a wasted round trip on every one of them.
  const [events, turns, event] = await Promise.all([
    listEvents(id),
    finished ? listTurns(id) : Promise.resolve([]),
    game.tournament ? getGameTournament(id) : Promise.resolve(null),
  ]);

  return (
    /* Wider than the lobby's 1180px on purpose. The three columns are fluid now, so a narrow cap
       stops being a reading-width guard and becomes the thing pinching the side rails — at 1920px
       a 1400px cap left them at 220px each with 500px of empty page beside them. */
    <main className="mx-auto w-full max-w-[2200px] flex-1 px-5 py-8">
      {/* The actions used to sit in a bar of their own above the status row, which cost a whole
          row of vertical space to hold two small buttons. They ride the status row now. */}
      {finished ? (
        <Replay
          game={game}
          apiUrl={apiUrl}
          events={events}
          turns={turns}
          event={event}
          actions={<GameActions pgnHref={pgnUrl(id)} />}
        />
      ) : (
        <GameView
          game={game}
          apiUrl={apiUrl}
          initialEvents={events}
          event={event}
          actions={<GameActions pgnHref={pgnUrl(id)} />}
        />
      )}
    </main>
  );
}
