"""credits as a granted balance

Revision ID: 1ff6aabe4e50
Revises: 96e852863cb5
Create Date: 2026-08-25 12:29:36.347741
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1ff6aabe4e50"
down_revision: str | None = "96e852863cb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_registry", sa.Column("credit_cost", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("model_registry", sa.Column("credit_cost_override", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("credit_balance", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credit_balance")
    op.drop_column("model_registry", "credit_cost_override")
    op.drop_column("model_registry", "credit_cost")
    # ### end Alembic commands ###
