"""a game is reconciled against what openrouter billed

Revision ID: 2a1ab14d70f5
Revises: 1b65e05c166c
Create Date: 2026-09-26 23:50:10.416936
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2a1ab14d70f5"
down_revision: str | None = "1b65e05c166c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unrecorded_generations",
        sa.Column("generation_id", sa.Text(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column(
            "found_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_unrecorded_generations_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("generation_id", name=op.f("pk_unrecorded_generations")),
    )
    op.create_index(
        op.f("ix_unrecorded_generations_game_id"),
        "unrecorded_generations",
        ["game_id"],
        unique=False,
    )
    op.add_column(
        "games", sa.Column("billed_usd", sa.Numeric(precision=16, scale=8), nullable=True)
    )
    op.add_column("games", sa.Column("billed_requests", sa.Integer(), nullable=True))
    op.add_column(
        "games", sa.Column("billed_checked_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "games", sa.Column("billing_checks", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "games", sa.Column("billing_anchor_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("games", sa.Column("billing_seq", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "billing_seq")
    op.drop_column("games", "billing_anchor_at")
    op.drop_column("games", "billing_checks")
    op.drop_column("games", "billed_checked_at")
    op.drop_column("games", "billed_requests")
    op.drop_column("games", "billed_usd")
    op.drop_index(op.f("ix_unrecorded_generations_game_id"), table_name="unrecorded_generations")
    op.drop_table("unrecorded_generations")
    # ### end Alembic commands ###
