"""add transcript_messages

Revision ID: 36c11953ef3b
Revises: 5397d1cffe2d
Create Date: 2026-08-15 17:07:14.520146
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "36c11953ef3b"
down_revision: str | None = "5397d1cffe2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcript_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_call_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_transcript_messages_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_transcript_messages_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name=op.f("fk_transcript_messages_turn_id_turns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_messages")),
        sa.UniqueConstraint("player_id", "seq", name="uq_transcript_messages_player_id_seq"),
    )
    op.create_index(
        op.f("ix_transcript_messages_game_id"), "transcript_messages", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_messages_player_id"), "transcript_messages", ["player_id"], unique=False
    )
    op.create_index(
        "ix_transcript_messages_player_id_seq",
        "transcript_messages",
        ["player_id", "seq"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_messages_turn_id"), "transcript_messages", ["turn_id"], unique=False
    )
    op.add_column(
        "players", sa.Column("transcript_seq", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "transcript_seq")
    op.drop_index(op.f("ix_transcript_messages_turn_id"), table_name="transcript_messages")
    op.drop_index("ix_transcript_messages_player_id_seq", table_name="transcript_messages")
    op.drop_index(op.f("ix_transcript_messages_player_id"), table_name="transcript_messages")
    op.drop_index(op.f("ix_transcript_messages_game_id"), table_name="transcript_messages")
    op.drop_table("transcript_messages")
    # ### end Alembic commands ###
