"""per-player provider routing

Revision ID: 45de46a988d0
Revises: de5fd691c11e
Create Date: 2026-08-15 22:07:01.511266
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "45de46a988d0"
down_revision: str | None = "de5fd691c11e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column(
            "provider_routing",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "provider_routing")
    # ### end Alembic commands ###
