"""purchases bought through paddle

Revision ID: 475c88e29301
Revises: 2a1ab14d70f5
Create Date: 2026-09-27 14:33:03.803606
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "475c88e29301"
down_revision: str | None = "2a1ab14d70f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("paddle_transaction_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("credited", "unmatched", name="purchasestatus", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("paddle_price_id", sa.Text(), nullable=True),
        sa.Column("paddle_customer_id", sa.Text(), nullable=True),
        sa.Column("credit_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("grand_total", sa.Text(), nullable=False),
        sa.Column("tax", sa.Text(), nullable=True),
        sa.Column("fee", sa.Text(), nullable=True),
        sa.Column("earnings", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_purchases_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint(
            "paddle_transaction_id", name=op.f("uq_purchases_paddle_transaction_id")
        ),
    )
    op.create_index(op.f("ix_purchases_status"), "purchases", ["status"], unique=False)
    op.create_index(op.f("ix_purchases_user_id"), "purchases", ["user_id"], unique=False)
    op.create_table(
        "purchase_adjustments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("paddle_adjustment_id", sa.Text(), nullable=False),
        sa.Column("purchase_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("amount", sa.Text(), nullable=False),
        sa.Column("credit_delta_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_purchase_adjustments_purchase_id_purchases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_adjustments")),
        sa.UniqueConstraint(
            "paddle_adjustment_id", name=op.f("uq_purchase_adjustments_paddle_adjustment_id")
        ),
    )
    op.create_index(
        op.f("ix_purchase_adjustments_purchase_id"),
        "purchase_adjustments",
        ["purchase_id"],
        unique=False,
    )
    op.add_column("credit_ledger", sa.Column("purchase_id", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_credit_ledger_purchase_id"), "credit_ledger", ["purchase_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_credit_ledger_purchase_id_purchases"),
        "credit_ledger",
        "purchases",
        ["purchase_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_credit_ledger_purchase_id_purchases"), "credit_ledger", type_="foreignkey"
    )
    op.drop_index(op.f("ix_credit_ledger_purchase_id"), table_name="credit_ledger")
    op.drop_column("credit_ledger", "purchase_id")
    op.drop_index(op.f("ix_purchase_adjustments_purchase_id"), table_name="purchase_adjustments")
    op.drop_table("purchase_adjustments")
    op.drop_index(op.f("ix_purchases_user_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_status"), table_name="purchases")
    op.drop_table("purchases")
    # ### end Alembic commands ###
