"""count compactions per seat

One integer with a server default, so existing seats read 0 — which is what "never compacted"
means and exactly right for every game played before ADR-0018.

Revision ID: 4a520d6bd632
Revises: 261b22004cff
Create Date: 2026-08-27 18:23:51.516347
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a520d6bd632"
down_revision: str | None = "261b22004cff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players", sa.Column("compactions", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "compactions")
    # ### end Alembic commands ###
