"""initial schema

Revision ID: 5397d1cffe2d
Revises:
Create Date: 2026-08-15 16:25:40.519348
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5397d1cffe2d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("openrouter_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("prompt_usd_per_token", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("completion_usd_per_token", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column(
            "supports_reasoning", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("supports_tools", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_free", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_registry")),
    )
    op.create_index(
        op.f("ix_model_registry_openrouter_id"), "model_registry", ["openrouter_id"], unique=True
    )
    op.create_index(
        op.f("ix_model_registry_provider"), "model_registry", ["provider"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clerk_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True)
    op.create_table(
        "games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "finished",
                "aborted",
                name="gamestatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("start_fen", sa.Text(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("1-0", "0-1", "1/2-1/2", "*", name="gameresult", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "termination",
            sa.Enum(
                "checkmate",
                "stalemate",
                "threefold_repetition",
                "fifty_move_rule",
                "insufficient_material",
                "resignation",
                "agreed_draw",
                "illegal_move_forfeit",
                "error_forfeit",
                "timeout",
                "budget_exceeded",
                "context_exceeded",
                "ply_cap",
                "adjudication",
                "abandoned",
                name="termination",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("termination_detail", sa.Text(), nullable=True),
        sa.Column(
            "winner_colour",
            sa.Enum("white", "black", name="colour", native_enum=False, length=40),
            nullable=True,
        ),
        sa.Column("ply_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("event_seq", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_ranked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "trash_talk_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("max_illegal_retries", sa.Integer(), server_default="5", nullable=False),
        sa.Column("max_plies", sa.Integer(), server_default="300", nullable=False),
        sa.Column(
            "auto_threefold_draw", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "auto_fifty_move_draw", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("tool_schema_version", sa.Text(), nullable=True),
        sa.Column("max_usd", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column(
            "total_cost_usd", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_games_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    op.create_index(
        op.f("ix_games_created_by_user_id"), "games", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_games_is_ranked"), "games", ["is_ranked"], unique=False)
    op.create_index(op.f("ix_games_status"), "games", ["status"], unique=False)
    op.create_index("ix_games_status_created_at", "games", ["status", "created_at"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("rating_deviation", sa.Float(), nullable=False),
        sa.Column("volatility", sa.Float(), nullable=False),
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "computed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_registry.id"],
            name=op.f("fk_ratings_model_id_model_registry"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
        sa.UniqueConstraint("model_id", "period", name="uq_ratings_model_id_period"),
    )
    op.create_index(op.f("ix_ratings_model_id"), "ratings", ["model_id"], unique=False)
    op.create_index(op.f("ix_ratings_period"), "ratings", ["period"], unique=False)
    op.create_table(
        "usage_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("games_started", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "usd_spent", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_ledger_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger")),
        sa.UniqueConstraint("user_id", "day", name="uq_usage_ledger_user_id_day"),
    )
    op.create_index(op.f("ix_usage_ledger_day"), "usage_ledger", ["day"], unique=False)
    op.create_index(op.f("ix_usage_ledger_user_id"), "usage_ledger", ["user_id"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "failed",
                name="analysisstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("engine", sa.Text(), nullable=True),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_analysis_jobs_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    op.create_index(op.f("ix_analysis_jobs_game_id"), "analysis_jobs", ["game_id"], unique=True)
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_table(
        "game_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "game_started",
                "turn_started",
                "thinking",
                "tool_called",
                "illegal_attempt",
                "move_made",
                "message_sent",
                "draw_offered",
                "game_ended",
                name="eventtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_game_events_game_id_games"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_events")),
        sa.UniqueConstraint("game_id", "seq", name="uq_game_events_game_id_seq"),
    )
    op.create_index(op.f("ix_game_events_game_id"), "game_events", ["game_id"], unique=False)
    op.create_index("ix_game_events_game_id_seq", "game_events", ["game_id", "seq"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column(
            "colour",
            sa.Enum("white", "black", name="colour", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum("model", "human", "engine", name="playerkind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("persona", sa.Text(), nullable=True),
        sa.Column("system_prompt_version", sa.Text(), nullable=True),
        sa.Column(
            "sampling", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("illegal_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("forfeited", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_cost_usd", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_players_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_registry.id"],
            name=op.f("fk_players_model_id_model_registry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_players_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("game_id", "colour", name="uq_players_game_id_colour"),
    )
    op.create_index(op.f("ix_players_game_id"), "players", ["game_id"], unique=False)
    op.create_index(op.f("ix_players_model_id"), "players", ["model_id"], unique=False)
    op.create_index(op.f("ix_players_user_id"), "players", ["user_id"], unique=False)
    op.create_table(
        "turns",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("ply_number", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                "forfeited",
                name="turnstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("illegal_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tool_call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llm_call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_turns_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_turns_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    op.create_index(op.f("ix_turns_game_id"), "turns", ["game_id"], unique=False)
    op.create_index(op.f("ix_turns_player_id"), "turns", ["player_id"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("model_slug", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning_text", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("payload_ref", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_llm_calls_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_llm_calls_turn_id_turns"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
        sa.UniqueConstraint("turn_id", "sequence", name="uq_llm_calls_turn_id_sequence"),
    )
    op.create_index(op.f("ix_llm_calls_game_id"), "llm_calls", ["game_id"], unique=False)
    op.create_index(op.f("ix_llm_calls_model_slug"), "llm_calls", ["model_slug"], unique=False)
    op.create_index(op.f("ix_llm_calls_turn_id"), "llm_calls", ["turn_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=True),
        sa.Column("turn_id", sa.BigInteger(), nullable=True),
        sa.Column("ply_number", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "pending",
                "approved",
                "blocked",
                name="moderationstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("moderation_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_messages_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_messages_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_messages_turn_id_turns"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_game_id"), "messages", ["game_id"], unique=False)
    op.create_index(
        op.f("ix_messages_moderation_status"), "messages", ["moderation_status"], unique=False
    )
    op.create_index(op.f("ix_messages_player_id"), "messages", ["player_id"], unique=False)
    op.create_index(op.f("ix_messages_turn_id"), "messages", ["turn_id"], unique=False)
    op.create_table(
        "plies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=True),
        sa.Column("ply_number", sa.Integer(), nullable=False),
        sa.Column(
            "colour",
            sa.Enum("white", "black", name="colour", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("san", sa.Text(), nullable=False),
        sa.Column("uci", sa.Text(), nullable=False),
        sa.Column("fen_before", sa.Text(), nullable=False),
        sa.Column("fen_after", sa.Text(), nullable=False),
        sa.Column("is_capture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_check", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_checkmate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_castling", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_en_passant", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("promotion", sa.String(length=1), nullable=True),
        sa.Column("think_ms", sa.Integer(), nullable=True),
        sa.Column("eval_before_cp", sa.Integer(), nullable=True),
        sa.Column("eval_after_cp", sa.Integer(), nullable=True),
        sa.Column("cp_loss", sa.Integer(), nullable=True),
        sa.Column("classification", sa.Text(), nullable=True),
        sa.Column("mate_in", sa.Integer(), nullable=True),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("engine_depth", sa.Integer(), nullable=True),
        sa.Column("analysed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_plies_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_plies_turn_id_turns"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plies")),
        sa.UniqueConstraint("game_id", "ply_number", name="uq_plies_game_id_ply_number"),
    )
    op.create_index(op.f("ix_plies_game_id"), "plies", ["game_id"], unique=False)
    op.create_index(op.f("ix_plies_turn_id"), "plies", ["turn_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_tool_calls_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_tool_calls_turn_id_turns"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint("turn_id", "sequence", name="uq_tool_calls_turn_id_sequence"),
    )
    op.create_index(op.f("ix_tool_calls_game_id"), "tool_calls", ["game_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_name"), "tool_calls", ["name"], unique=False)
    op.create_index(op.f("ix_tool_calls_turn_id"), "tool_calls", ["turn_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_calls_turn_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_name"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_game_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_plies_turn_id"), table_name="plies")
    op.drop_index(op.f("ix_plies_game_id"), table_name="plies")
    op.drop_table("plies")
    op.drop_index(op.f("ix_messages_turn_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_player_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_moderation_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_game_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_llm_calls_turn_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_model_slug"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_game_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_turns_player_id"), table_name="turns")
    op.drop_index(op.f("ix_turns_game_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index(op.f("ix_players_user_id"), table_name="players")
    op.drop_index(op.f("ix_players_model_id"), table_name="players")
    op.drop_index(op.f("ix_players_game_id"), table_name="players")
    op.drop_table("players")
    op.drop_index("ix_game_events_game_id_seq", table_name="game_events")
    op.drop_index(op.f("ix_game_events_game_id"), table_name="game_events")
    op.drop_table("game_events")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_game_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_usage_ledger_user_id"), table_name="usage_ledger")
    op.drop_index(op.f("ix_usage_ledger_day"), table_name="usage_ledger")
    op.drop_table("usage_ledger")
    op.drop_index(op.f("ix_ratings_period"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_model_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index("ix_games_status_created_at", table_name="games")
    op.drop_index(op.f("ix_games_status"), table_name="games")
    op.drop_index(op.f("ix_games_is_ranked"), table_name="games")
    op.drop_index(op.f("ix_games_created_by_user_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_model_registry_provider"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_openrouter_id"), table_name="model_registry")
    op.drop_table("model_registry")
    # ### end Alembic commands ###
