"""tournaments

Revision ID: 5608a2e4cd6e
Revises: 5f2b82084ba9
Create Date: 2026-08-25 23:39:36.953171
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5608a2e4cd6e"
down_revision: str | None = "5f2b82084ba9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "paused",
                "finished",
                "abandoned",
                name="tournamentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("double", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rounds", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "field_filter",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("max_concurrent", sa.Integer(), server_default="1", nullable=False),
        sa.Column("max_usd", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("max_plies_per_game", sa.Integer(), server_default="300", nullable=False),
        sa.Column("max_usd_per_game", sa.Numeric(precision=16, scale=8), nullable=True),
        sa.Column("is_ranked", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "total_cost_usd", sa.Numeric(precision=16, scale=8), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournaments")),
    )
    op.create_index(op.f("ix_tournaments_slug"), "tournaments", ["slug"], unique=True)
    op.create_index(op.f("ix_tournaments_status"), "tournaments", ["status"], unique=False)
    op.create_table(
        "tournament_entrants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("model_slug", sa.Text(), nullable=False),
        sa.Column("quantization", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("withdrawn", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_registry.id"],
            name=op.f("fk_tournament_entrants_model_id_model_registry"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_entrants_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_entrants")),
        sa.UniqueConstraint("tournament_id", "key", name="uq_tournament_entrants_key"),
    )
    op.create_index(
        op.f("ix_tournament_entrants_model_id"), "tournament_entrants", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_entrants_tournament_id"),
        "tournament_entrants",
        ["tournament_id"],
        unique=False,
    )
    op.create_table(
        "tournament_games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("white_key", sa.Text(), nullable=False),
        sa.Column("black_key", sa.Text(), nullable=True),
        sa.Column("white_score", sa.Float(), nullable=True),
        sa.Column("abandoned_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_tournament_games_game_id_games"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name=op.f("fk_tournament_games_tournament_id_tournaments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tournament_games")),
        sa.UniqueConstraint(
            "tournament_id",
            "round_number",
            "white_key",
            "black_key",
            name="uq_tournament_games_pairing",
        ),
    )
    op.create_index(
        op.f("ix_tournament_games_game_id"), "tournament_games", ["game_id"], unique=False
    )
    op.create_index(
        "ix_tournament_games_round",
        "tournament_games",
        ["tournament_id", "round_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_games_round_number"), "tournament_games", ["round_number"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_games_tournament_id"),
        "tournament_games",
        ["tournament_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tournament_games_tournament_id"), table_name="tournament_games")
    op.drop_index(op.f("ix_tournament_games_round_number"), table_name="tournament_games")
    op.drop_index("ix_tournament_games_round", table_name="tournament_games")
    op.drop_index(op.f("ix_tournament_games_game_id"), table_name="tournament_games")
    op.drop_table("tournament_games")
    op.drop_index(op.f("ix_tournament_entrants_tournament_id"), table_name="tournament_entrants")
    op.drop_index(op.f("ix_tournament_entrants_model_id"), table_name="tournament_entrants")
    op.drop_table("tournament_entrants")
    op.drop_index(op.f("ix_tournaments_status"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_slug"), table_name="tournaments")
    op.drop_table("tournaments")
    # ### end Alembic commands ###
