"""credit ledger

Revision ID: 5f2b82084ba9
Revises: 1ff6aabe4e50
Create Date: 2026-08-25 14:46:04.368088
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5f2b82084ba9"
down_revision: str | None = "1ff6aabe4e50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "game_start",
                "admin_grant",
                "admin_revoke",
                "refund",
                name="creditreason",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("game_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_credit_ledger_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_credit_ledger_game_id_games"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_credit_ledger_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_ledger")),
    )
    op.create_index(
        op.f("ix_credit_ledger_actor_user_id"), "credit_ledger", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_credit_ledger_game_id"), "credit_ledger", ["game_id"], unique=False)
    op.create_index(op.f("ix_credit_ledger_reason"), "credit_ledger", ["reason"], unique=False)
    op.create_index(op.f("ix_credit_ledger_user_id"), "credit_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # An opening entry for every balance that predates the ledger.
    #
    # Without it, AUTH-13's invariant — a balance equals the sum of its history — is false on day
    # one for anyone already holding credits, and the first thing anyone audits is the account that
    # does not add up. Recorded as a grant with no actor, which is exactly what it was: credits
    # that exist because the system said so, before anyone was recording why.
    op.execute(
        sa.text(
            """
            INSERT INTO credit_ledger (user_id, delta, balance_after, reason, note, created_at)
            SELECT id, credit_balance, credit_balance, 'admin_grant',
                   'opening balance, recorded when the ledger was introduced', now()
            FROM users
            WHERE credit_balance <> 0
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credit_ledger_user_id"), table_name="credit_ledger")
    op.drop_index(op.f("ix_credit_ledger_reason"), table_name="credit_ledger")
    op.drop_index(op.f("ix_credit_ledger_game_id"), table_name="credit_ledger")
    op.drop_index(op.f("ix_credit_ledger_actor_user_id"), table_name="credit_ledger")
    op.drop_table("credit_ledger")
    # ### end Alembic commands ###
