"""draw rules are claimable, not automatic

Revision ID: 81d212a800d5
Revises: 4a520d6bd632
Create Date: 2026-08-28 15:05:55.828895

Threefold repetition and the fifty-move rule become a claim (FIDE 9.2, 9.3) rather than something
the referee applies on both players' behalf. See ADR-0020.

**Existing rows are deliberately not backfilled.** A game already in progress was created under
prompt v1 and tool schema v1, so it was never told the rules and has no `claim_draw` to call. Turning
the automatic draw off for those games would leave them ending only at the fivefold backstop — the
worst of both. A v1 game keeps v1 rules; the new default applies to games created from here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "81d212a800d5"
down_revision: str | None = "4a520d6bd632"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games",
        "auto_threefold_draw",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "auto_fifty_move_draw",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games",
        "auto_fifty_move_draw",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "auto_threefold_draw",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
