"""credit reservations for custom amounts

Revision ID: 871759676bb6
Revises: 475c88e29301
Create Date: 2026-09-28 14:04:18.933694
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "871759676bb6"
down_revision: str | None = "475c88e29301"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("credit_usd", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "consumed",
                "released",
                name="reservationstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("paddle_transaction_id", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_credit_reservations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_reservations")),
        sa.UniqueConstraint(
            "paddle_transaction_id", name=op.f("uq_credit_reservations_paddle_transaction_id")
        ),
    )
    op.create_index(
        op.f("ix_credit_reservations_expires_at"),
        "credit_reservations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_reservations_status"), "credit_reservations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_credit_reservations_user_id"), "credit_reservations", ["user_id"], unique=False
    )
    op.add_column("purchases", sa.Column("reservation_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_purchases_reservation_id"), "purchases", ["reservation_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_purchases_reservation_id_credit_reservations"),
        "purchases",
        "credit_reservations",
        ["reservation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_purchases_reservation_id_credit_reservations"), "purchases", type_="foreignkey"
    )
    op.drop_index(op.f("ix_purchases_reservation_id"), table_name="purchases")
    op.drop_column("purchases", "reservation_id")
    op.drop_index(op.f("ix_credit_reservations_user_id"), table_name="credit_reservations")
    op.drop_index(op.f("ix_credit_reservations_status"), table_name="credit_reservations")
    op.drop_index(op.f("ix_credit_reservations_expires_at"), table_name="credit_reservations")
    op.drop_table("credit_reservations")
    # ### end Alembic commands ###
