"""hugging face id for open-weights brackets

Revision ID: a4a38af6daa1
Revises: 5608a2e4cd6e
Create Date: 2026-08-25 23:40:27.020177
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a4a38af6daa1"
down_revision: str | None = "5608a2e4cd6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_registry", sa.Column("hugging_face_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_registry", "hugging_face_id")
    # ### end Alembic commands ###
