"""tournament active window and daily game cap

Revision ID: cc32ea1cb989
Revises: a4a38af6daa1
Create Date: 2026-08-26 11:43:54.143522
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc32ea1cb989"
down_revision: str | None = "a4a38af6daa1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournaments", sa.Column("active_from", sa.Time(), nullable=True))
    op.add_column("tournaments", sa.Column("active_until", sa.Time(), nullable=True))
    op.add_column("tournaments", sa.Column("max_games_per_day", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournaments", "max_games_per_day")
    op.drop_column("tournaments", "active_until")
    op.drop_column("tournaments", "active_from")
    # ### end Alembic commands ###
