"""provider routing and model endpoints

Revision ID: de5fd691c11e
Revises: 36c11953ef3b
Create Date: 2026-08-15 21:45:35.130427
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "de5fd691c11e"
down_revision: str | None = "36c11953ef3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_endpoints",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.Text(), nullable=False),
        sa.Column("quantization", sa.Text(), nullable=True),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("supports_tools", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("max_completion_tokens", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "refreshed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_registry.id"],
            name=op.f("fk_model_endpoints_model_id_model_registry"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_endpoints")),
        sa.UniqueConstraint(
            "model_id", "provider_name", name="uq_model_endpoints_model_id_provider_name"
        ),
    )
    op.create_index(
        op.f("ix_model_endpoints_model_id"), "model_endpoints", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_endpoints_provider_name"), "model_endpoints", ["provider_name"], unique=False
    )
    op.add_column(
        "games",
        sa.Column(
            "provider_routing",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "provider_routing")
    op.drop_index(op.f("ix_model_endpoints_provider_name"), table_name="model_endpoints")
    op.drop_index(op.f("ix_model_endpoints_model_id"), table_name="model_endpoints")
    op.drop_table("model_endpoints")
    # ### end Alembic commands ###
